### ISSUE TITLE
(improvement) use sqrtf() on ESP32

### ISSUE THREAD

**Issue by softhack007** [kosme/arduinoFFT#75]
Hi,  
thanks for this great library!

One idea to improve speed would be to use `sqrtf()` on platforms where newlib is available, for example on ESP32. The '..f' versions are optimized for float (instead of double). In my own experiments - forward FFT on 512 samples in float - using sqrtf() has created up to 50% speedup.

btw, are there plans already fo a new release? The `develop` branch seems to be quite stable.

Kind regards, Frank
https://github.com/kosme/arduinoFFT/blob/bd164d1c3ddb755a57c671773ad0106b57fff6fd/src/arduinoFFT.h#L49-L55

https://github.com/kosme/arduinoFFT/blob/bd164d1c3ddb755a57c671773ad0106b57fff6fd/src/arduinoFFT.h#L428-L434

**Comment by kosme** [comment]
@softhack007 Thanks for your suggestions. I will consider them. I am currently working on a new release using some of the features on the `develop` branch. I am still trying to figure out how to proceed since the `develop` branch introduced a major break on the API, specifically the templating. AVR chips make no difference between `float` and `double` variables, so templating is useless on those chips. Non-AVR chips have more memory and higher clock speeds, and I could not think of a reason why anyone would use the `float` data type. Your mention of the functions optimized for `float` answered that question.
